#!/usr/bin/perl -W

%glyph = ();

print "#include <stdlib.h>\n";
print "#include \"rufl_internal.h\"\n";
print "const struct rufl_glyph_map_entry rufl_glyph_map[] = {\n";

while (<>) {
	if (/^([0-9A-F]{4});([a-zA-Z0-9]+);/) {
		$glyph{$2} = $1;
	}
}

foreach $z (sort keys %glyph) {
	print "\t{\"$z\", 0x$glyph{$z}},\n";
}

print "};\n";
print "const size_t rufl_glyph_map_size = sizeof rufl_glyph_map /\n";
print "		sizeof rufl_glyph_map[0];\n";
